services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  strapi:
    build:
      context: .
      dockerfile: docker/strapi.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      NODE_ENV: development
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    ports:
      - "1337:1337"

  frontend:
    build:
      context: .
      dockerfile: docker/nextjs.Dockerfile
      target: development
    volumes:
      - ./apps/frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend-next-cache:/app/.next
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_STRAPI_API_URL: http://localhost:1337
      STRAPI_API_URL: http://strapi:1337
      WATCHPACK_POLLING: true
      NEXT_TELEMETRY_DISABLED: 1
      HOSTNAME: 0.0.0.0
      

volumes:
  postgres-data:
  frontend_node_modules:
  frontend-next-cache:
